version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_sigev
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    command: npm start
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge
