version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_sigev
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  server:
    depends_on:
      - postgres
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
