version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_sigev
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  server:
    build: ./docker/server
    command: npm start
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - postgres-compose-network

  # front:
  #   build: ./docker/client
  #   command: npm start
  #   ports:
  #     - "8080:3000"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:3000
  #   networks:
  #     - postgres-compose-network
  #   depends_on:
  #     - server

networks:
  postgres-compose-network:
    driver: bridge
